name: Processing
on:
  push:
    branches:
      - master
      - addci
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python 3.10
        uses: actions/checkout@v2
        with:
          python-version: 3.10
      - name: Processing Testing
        run: |
          python calc.py